### ISSUE TITLE
feature-request: sks: export kubeconfig string (or even separate credentials) of the resource

### ISSUE THREAD

**Issue by Strangerxxx** [exoscale/terraform-provider-exoscale#131]
Hello!
I'd really like to have ability not just create SKS cluster using terraform, but at the same time get the connection credentials to use it in-place with kubernetes/helm terraform providers.
It is kind of enabler for me to use SKS on Exoscale.
As I can understand there is pretty straight forward possibility to implement such feature.
However if there is any cons which prevents of doing so please let me know.

PS: most of managed kubernetes providers like DO, GCP, AWS, YACloud have this ability.

**Comment by tstrohmeier** [comment]
+1

**Comment by retrack** [comment]
We had debated internally already before your issue and had concluded that it was not a safe practice to do. Happy to revisit however especially if other providers behave like so.

**Comment by secustor** [comment]
Examples of how other cloud providers handle this situation:
 
- Azure:
  directly exposes the kubeconfig as attributes. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kube_config_raw
- GCP: 
  exposes a datasource https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_examples/gke/main.tf#L26
- AWS: 
  does as Exoscale requires the usage of the kubeconfig exec plugin https://github.com/WesleyCharlesBlake/terraform-aws-eks/blob/081b9c703a4e23db0bbc9024c08e5cc62c7c08f4/config.tf#L37

**Comment by Strangerxxx** [comment]
> * AWS:
>   does as Exoscale requires the usage of the kubeconfig exec plugin

Could you explain how I may use exoscale cli as a kubeconfig exec plugin? @secustor

If I'm able to use it as plugin, than there is no reason to expose kubeconfig, unfortunately I did not found any documented example of this way usage of exoscale cli (

**Comment by secustor** [comment]
It eases the usage in CI systems as the user does not have to install and configure the `exo` cli separately to Terraform. 

This is the output of `exo compute sks kubeconfig --help`: 
```
    apiVersion: v1
    kind: Config
    clusters:
    - name: my-sks-cluster
      cluster:
        certificate-authority-data: **BASE64-ENCODED CLUSTER CERTIFICATE**
        server: https://153fcc53-1197-46ae-a8e0-ccf6d09efcb0.sks-ch-gva-2.exo.io:443
    users:
    - name: exo@my-sks-cluster
      user:
        # The "exec" section replaces "client-certificate-data"/"client-key-data"
        exec:
          apiVersion: "client.authentication.k8s.io/v1beta1"
          command: exo
          args:
          - sks
          - kubeconfig
          - my-sks-cluster
          - --zone=ch-gva-2
          - --exec-credential
          - user
    contexts:
    - name: my-sks-cluster
      context:
        cluster: my-sks-cluster
        user: exo@my-sks-cluster
    current-context: my-sks-cluster
```
