### ISSUE TITLE
[Feature Request]: provider profil parameter

### ISSUE THREAD

**Issue by fegger-ducksify** [exoscale/terraform-provider-exoscale#358]
### What feature would you like to have in the provider?

The following provider-level settings are supported, either via [HCL parameters](https://www.terraform.io/docs/configuration/providers.html) or environment variables.

It would be useful to have a profile parameter, similar to what AWS provides.

Using the Exoscale Terraform provider with Atlantis is challenging when managing multiple IAM keys for different environments.

**Comment by sauterp** [comment]
Hi,
thank you for this request.

Are you only interested in the "profile" parameter?)

I interpret your request to be, that you would like our provider to get credentials from the `~/.config/exoscale/exoscale.toml` file when you specify the "account" parameter(as a pendant to "profile"). Did I understand this correctly?

Could you also share more details on the challenges you face when using our provider with Atlantis, please?

**Comment by fegger-ducksify** [comment]
Hi Philipp,

Yes, you understood correctly. I need to use the profiles stored in ~/.config/exoscale/exoscale.toml. In Exoscale, we have multiple organizations, each with its own IAM keys. I need to manage resources within the same Terraform plan.


For Atlantis in SKS a way to provide secrets is to set helm values like this
```
  environmentSecrets:
    - name: EXOSCALE_API_KEY
      secretKeyRef:
        name: providers-secret
        key: EXOSCALE_API_KEY
    - name: EXOSCALE_API_SECRET
      secretKeyRef:
        name: providers-secret
        key: EXOSCALE_API_SECRET

  extraVolumeMounts:
    - name: edgerc
      mountPath: /home/atlantis
```
terraform offer the possibility to use alias for provider, we can have for example multiple aws ressources with different profile

```
provider "aws" {
    alias = "exo1"
    region = var.exoscale_zone_default
    profile = "exo1"
    endpoints {
      s3 = "https://sos-${var.exoscale_zone_default}.exo.io"
    }
}
``` 
```
provider "aws" {
    alias = "exo2"
    region = var.exoscale_zone_default
    profile = "exo2"
    endpoints {
      s3 = "https://sos-${var.exoscale_zone_default}.exo.io"
    }
}
``` 

Using environment variables restricts us to a single set of credentials

Is that make sense?
